#!/usr/bin/env bash
set -euo pipefail
python3 - <<'PY'
from pathlib import Path
p=Path('AirliftCanaryExploit.m'); s=p.read_text()
if '#import "AirliftBooksState.h"' not in s:s=s.replace('#import "MCMFilzaIntegration.h"','#import "MCMFilzaIntegration.h"\n#import "AirliftBooksState.h"')
old='''            BOOL booksAbsent = FZACTrackedBooksAbsent(afc);\n            BOOL freshPaths = !FZACAFCExists(afc, source) &&\n                !FZACAFCExists(afc, linkDestination) &&\n                !FZACAFCExists(afc, recovered) &&\n                !FZACAFCExists(afc, targetThroughLink);\n            result[@"BooksPreimageAbsent"] = @(booksAbsent);\n            result[@"FreshGeneratedPaths"] = @(freshPaths);\n            if (!booksAbsent || !freshPaths || !archive.length || !books.length) {\n                result[@"FailureStage"] = @"preflight";\n                break;\n            }\n            cleanupAuthorized = YES;'''
new='''            NSString *snapshotRoot = [NSTemporaryDirectory() stringByAppendingPathComponent:[@"airlift-books-" stringByAppendingString:token]];\n            NSDictionary *snapshotResult = FZACSnapshotBooksState(afc, snapshotRoot);\n            NSData *snapshotData = [NSData dataWithContentsOfFile:[snapshotRoot stringByAppendingPathComponent:@"manifest.plist"]];\n            NSDictionary *snapshot = snapshotData ? [NSPropertyListSerialization propertyListWithData:snapshotData options:NSPropertyListImmutable format:nil error:nil] : nil;\n            BOOL booksStable = [snapshotResult[@"ok"] boolValue] && snapshot && FZACBooksStateMatchesSnapshot(afc, snapshotRoot, snapshot);\n            BOOL freshPaths = !FZACAFCExists(afc, source) && !FZACAFCExists(afc, linkDestination) && !FZACAFCExists(afc, recovered) && !FZACAFCExists(afc, targetThroughLink);\n            result[@"BooksSnapshot"] = snapshotResult ?: @{}; result[@"BooksPreimageStable"] = @(booksStable); result[@"FreshGeneratedPaths"] = @(freshPaths);\n            if (!booksStable || !freshPaths || !archive.length || !books.length) { result[@"FailureStage"] = @"preflight"; break; }\n            cleanupAuthorized = YES;'''
if old not in s and 'BooksPreimageStable' not in s:raise SystemExit('Airlift preflight pattern drifted; refusing unsafe patch')
s=s.replace(old,new)
old2='''            BOOL clean = cleanupFailures.count == 0 &&\n                !FZACAFCExists(afc, source) &&\n                !FZACAFCExists(afc, linkDestination) &&\n                !FZACAFCExists(afc, recovered) &&\n                FZACTrackedBooksAbsent(afc);\n            result[@"CleanupFailures"] = cleanupFailures;\n            result[@"CleanupComplete"] = @(clean);'''
new2='''            NSString *snapshotRoot = [NSTemporaryDirectory() stringByAppendingPathComponent:[@"airlift-books-" stringByAppendingString:token]];\n            NSDictionary *restore = FZACRestoreBooksState(afc, snapshotRoot);\n            BOOL clean = cleanupFailures.count == 0 && [restore[@"ok"] boolValue] && !FZACAFCExists(afc, source) && !FZACAFCExists(afc, linkDestination) && !FZACAFCExists(afc, recovered);\n            result[@"BooksRestore"] = restore ?: @{}; result[@"BooksRestoreVerified"] = @([restore[@"preimageVerified"] boolValue]); result[@"CleanupFailures"] = cleanupFailures; result[@"CleanupComplete"] = @(clean);\n            [[NSFileManager defaultManager] removeItemAtPath:snapshotRoot error:nil];'''
if old2 not in s and 'BooksRestoreVerified' not in s:raise SystemExit('Airlift cleanup pattern drifted; refusing unsafe patch')
s=s.replace(old2,new2);p.write_text(s)
PY
